variable "api_name_in" {}
variable "cognito_user_pool_id_in" {}
variable "var.vpc_automation_sqs_in" {}
variable "get_vpc_lambda_arn_in" {}
variable "var.aws_region_in" {}
variable "var.aws_account_in" {}
variable "var.sqs_queue_in" {}
variable "lambda_in" {}
variable "sqs_role_apigw_in" {}
